# Generated by Django 4.2 on 2023-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernumbers",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="code",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserAddress",
        ),
        migrations.DeleteModel(
            name="UserNumbers",
        ),
    ]
