# Generated by Django 4.2 on 2023-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
