# Generated by Django 4.2 on 2023-05-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_alter_propertybook_childern_alter_propertybook_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertybook",
            name="childern",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AlterField(
            model_name="propertybook",
            name="guest",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
