# Generated by Django 4.2 on 2023-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_alter_propertybook_childern_alter_propertybook_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default=" ", max_length=30),
            preserve_default=False,
        ),
    ]
